name: Gh-Pages

on: 
  push:
    branches: [master]    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2 #Only works with v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7